name: Deploy Python OpenAI Lambda on Merge

on:
  push:
    branches:
      - main  # mainブランチへのpushでトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files (debug)
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          ls -R

      - name: Run Amazon Linux 2 Docker build
        run: |
          docker run --rm -v "$GITHUB_WORKSPACE":/var/task public.ecr.aws/amazonlinux/amazonlinux:2023 bash -c "
            yum install -y python3.11 python3.11-pip zip gcc rust cargo &&
            python3.11 -m venv venv &&
            source venv/bin/activate &&
            pip install --upgrade pip &&
            pip install -r functions/call_openai/requirements.txt -t python/ &&
            mkdir -p package &&
            cp functions/call_openai/lambda_function.py package/ &&
            cp -r python/* package/ &&
            cd package &&
            zip -r9 ../function.zip .
          "

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1  # 東京リージョン

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name callopenai \
            --zip-file fileb://function.zip
